name = "mohamed-amer-portfolio"
pages_build_output_dir = "./dist"
compatibility_date = "2026-10-05"

[[d1_databases]]
binding = "PROJECTS_DB"
database_name = "mohamed-amer-projects"
database_id = "1c2b2b52-d000-4c22-af9f-afb561967873"
